- block:
  - name: Add RPM Fusion Repositorys
    dnf:
      name: 
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
      state: present
    vars:
      fedora_version: 34
    
  - name: Install Workstation Repositorys
    dnf:
      name:
        - fedora-workstation-repositories
      state: latest

  - name: Upgrade All Packages
    dnf:
      name: "*"
      state: latest

  - name: Install Packages for Kernel
    dnf: 
      name:
        - kernel-headers
        - kernel-devel
      state: latest

  - name: Install Packages Groups for OS
    dnf:
      name: 
        - "@Development Tools"
        - "@Development Libraries"
        - "@RPM Development Tools"
        
  - name: Install Useful Packages
    dnf:
      name:
        - fedora-packager
      state: latest

  - name: Execute autoremove
    dnf:
      autoremove: yes
      