- block:
  - name: INSTALL RPM FUSION REPOSITORYS
    dnf:
      name: 
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
      state: present
    #vars:
    #  fedora_version: 34

  - name: IMPORT KEY VSCODE
    ansible.builtin.rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: CREATE VSCODE FILE
    shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  - name: ADD DOCKER REPOSITORY
    get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: INSTALL WORKSTATION REPOSITORYS
    dnf:
      name: fedora-workstation-repositories
      state: latest

  - name: UPGRADE ALL PACKAGES
    dnf:
      name: "*"
      state: latest

  - name: INSTALL PACKAGES FOR KERNEL
    dnf: 
      name:
        - kernel-headers
        - kernel-devel
      state: latest

  - name: INSTALL PACKAGES GROUPS FOR OS
    dnf:
      name: 
        - "@Development Tools"
        - "@Development Libraries"
        - "@RPM Development Tools"
      state: latest
        
  - name: INSTALL USEFUL PACKAGES
    dnf:
      name: fedora-packager
      state: latest

  - name: UNINSTALL DEFAULT PACKAGES
    dnf: 
      name: 
        - xfburn
        - geany
        - pidgin
        - claws-mail
        - asunder
        - parole
        - pragha      
      state: absent

  - name: EXECUTE AUTOREMOVE COMMAND
    dnf:
      autoremove: yes
      