---
  - hosts: all
    become: True
    roles: 
      - ubuntu-security
    vars:
      ubuntu_user: freddy
      ubuntu_version: focal
      ubuntu_kernel_version: 5.4.0-77-generic   # $(uname -r), get data from ansible project
      ubuntu_host: XXX.YYY.ZZZ.VVV    # IP Address or localhost
      ubuntu_private_key_file: ~/.ssh/fcch-ssh
      ubuntu_port: 22