- block:
  - name: TOOLS FOR ARDUINO, RASPBERRY
    dnf:
      name:
        - arduino
        - fritzing
        - arm-image-installer
      state: latest

  - name: DEVELOPMENT, LANGUAGES AND FRAMEWORKS OF PROGRAMMING
    dnf:
      name:
        - sqlitebrowser
        - glade
        - php-cli
        - java
        - golang
        - gd
        - hugo
      state: latest

  - name: GRAPHICS DESIGN
    dnf:
      name: 
        - gimp
        - inkscape
        - inkscape-psd
        - inkscape-view
        - blender
        - dia
        - dia-CMOS
        - dia-Digital
        - dia-electric2
        - dia-electronic
        - dia-gnomeDIAicons
        - dia-optics
        - google-noto-sans-mono-fonts
      state: latest

  - name: WEB BROWSERS
    dnf:
      name:
      - firefox
      - chromium-freeworld
      - elinks
      - thunderbird
      state: latest

  - name: INSTALL GOOGLE CHROME
    dnf:
      name: google-chrome-stable
      enablerepo: google-chrome 
      state: latest

  - name: SSH SERVER
    dnf:
      name:
        - openssh-askpass
        - openssh-clients
        - openssh-server
        - openssh
        - sshpass
        - mosh
        - putty
      state: latest

  - name: KVM VIRTUALIZATION
    dnf:
      name: "@virtualization"
      state: latest

  - name: VIRTUALIZATION TOOLS
    dnf:
      name:
        - virt-install
        - virt-manager
        - virt-viewer
        - virt-what
        - bridge-utils
        - VirtualBox
      state: latest

  - name: INSTALL MARIADB
    dnf:
      name: 
        - mariadb-server
        - mariadb-server-utils
        - mycli
      state: latest

  - name: IMPORT KEY VSCODE
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: CREATE VSCODE FILE
    shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  - name: INSTALL VSCODE
    dnf:
      name: 
        - code
      state: latest

  - name: ADD DOCKER REPOSITORY
    get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: INSTALL DOCKER COMPOSE
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ kernel_name }}-{{ hardware_machine }}
      dest: /usr/local/bin/docker-compose 
      mode: "0755"

  - name: INSTALL DOCKER
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: ENABLE DOCKER DAEMON
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes

  - name: ADD ON GROUP DOCKER
    shell: usermod -a -G docker {{ fedora_user }}

  - name: ENABLE MARIADB DAEMON
    ansible.builtin.systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: ENABLE SSH DAEMON
    ansible.builtin.systemd:
      name: sshd
      state: started
      enabled: yes

  - name: ADD ON GROUP VBOXUSERS
    shell: usermod -a -G vboxusers {{ fedora_user }}

  - name: ADD ON GROUP QEMU
    shell: usermod -a -G qemu {{ fedora_user }}

  - name: ADD ON GROUP LIBVIRT
    shell: usermod -a -G libvirt {{ fedora_user }}
