- block:
  - name: Arduino, Raspberry
    dnf:
      name:
        - arduino
        - fritzing
        - arm-image-installer
      state: latest

  - name: Development and Languages of Programming
    dnf:
      name:
        - sqlitebrowser
        - glade
        - php-cli
        - java
        - golang
        - gd
      state: latest

  - name: Graphics Design
    dnf:
      name: 
        - gimp
        - inkscape
        - inkscape-psd
        - inkscape-view
        - blender
        - dia
        - dia-CMOS
        - dia-Digital
        - dia-electric2
        - dia-electronic
        - dia-gnomeDIAicons
        - dia-optics
      state: latest

  - name: Web Browsers
    dnf:
      name:
      - firefox
      - chromium-freeworld
      - elinks
      - thunderbird
      state: latest

  - name: SSH Server
    dnf:
      name:
        - openssh-askpass
        - openssh-clients
        - openssh-server
        - openssh
        - sshpass
        - mosh
        - putty
      state: latest

  - name: Virtualization KVM
    dnf:
      name: "@virtualization"
      state: latest

  - name: Virtualization Tools
    dnf:
      name:
        - virt-install
        - virt-manager
        - virt-viewer
        - virt-what
        - bridge-utils
        - VirtualBox
      state: latest

  - name: Install Google Chrome
    dnf:
      name: google-chrome-stable
      enablerepo: google-chrome 
      state: latest

  - name: Install MariaDB
    dnf:
      name: 
        - mariadb-server
        - mariadb-server-utils
        - mycli
      state: latest

  - name: Import key VSCode
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Create VSCode File
    shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  - name: Install VSCode
    dnf:
      name: 
        - code
      state: latest

  - name: Add Docker Repository
    get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ kernel_name }}-{{ hardware_machine }}
      dest: /usr/local/bin/docker-compose 
      mode: "0755"

  - name: Install Docker
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: Enable Docker Daemon
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add on Group Docker
    shell: usermod -a -G docker {{ fedora_user }}

  - name: Enable MariaDB Daemon
    ansible.builtin.systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: Enable SSH Daemon
    ansible.builtin.systemd:
      name: sshd
      state: started
      enabled: yes

  - name: Add on Group TCPDUMP
    shell: usermod -a -G tcpdump {{ fedora_user }}
    #vars:
    #  fedora_user: name_user

  - name: Add on Group WIRESHARK
    shell: usermod -a -G wireshark {{ fedora_user }}

  - name: Add on Group VBOXUSERS
    shell: usermod -a -G vboxusers {{ fedora_user }}

  - name: Add on Group QEMU
    shell: usermod -a -G qemu {{ fedora_user }}

  - name: Add on Group LIBVIRT
    shell: usermod -a -G libvirt {{ fedora_user }}
