- block:
  - name: Essentials Tools 
    dnf:
      name:
        - lightdm-gtk-greeter-settings
        - redhat-lsb-core
        - vim-enhanced 
        - curl
        - wget
        - whois
        - telnet
        - nmap 
        - git
        - gitg
        - nfs-utils
        - ntfs-3g
        - ntfsprogs
        - parted
        - gdisk
        - gparted
        - gpart
        - exfat-utils
        - fuse-exfat
        - gstreamer1-plugins-base
        - gstreamer1-plugin-openh264
        - gstreamer1-libav
        - gstreamer1-plugins-good
        - gstreamer1-libav
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-bad-free-extras
        - gstreamer1-plugins-good-extras
        - gstreamer1-plugins-ugly
        - gstreamer1-plugins-ugly-free
        - gstreamer1-libav
        - gstreamer1-plugins-good-gtk
        - gstreamer1-plugins-good-qt
        - ffmpeg
        - caca-utils
        - gstreamer1
        - faac
        - faad2
        - alsa-lib
        - alsa-plugins-pulseaudio
        - alsa-utils
        - arduino
        - fritzing
        - arm-image-installer
        - unrar
        - p7zip
        - p7zip-plugins
        - unrar
        - unzip
        - java
        - torbrowser-launcher
        - torsocks
        - tor
        - htop
        - gnome-system-monitor
        - brasero
        - pv
        - youtube-dl
        - dkms
        - axel
        - android-tools
        - zsh
        - smartmontools
        - speedtest-cli
        - gd
        - golang
        - putty
        - pwgen
        - rdesktop
        - sl
        - transmission
        - hexchat
        - intltool
        - iotop
        - itop
        - keepassxc
        - lua
        - telegram-desktop
        - testssl
        - tmux
        - terminator
        - sqlitebrowser
        - fdupes
        - figlet
        - mediainfo
        - mediainfo-gui
        - pdfmod
        - httpd-tools
        - httrack
        - linkchecker
        - ghex
        - gqrx
        - perl-Image-ExifTool
        - glade
        - python3-virtualenv
        - vinagre
        - vlc
        - soundconverter
        - peek
        - cups
        - cups-client
        - cups-libs
        - cups-pdf
        - hplip
        - hplip-libs
      state: latest  
  
  - name: Graphics Design
    dnf:
      name: 
        - gimp
        - inkscape
        - inkscape-psd
        - inkscape-view
        - blender
        - dia
        - dia-CMOS
        - dia-Digital
        - dia-electric2
        - dia-electronic
        - dia-gnomeDIAicons
        - dia-optics
      state: latest

  - name: Web Browsers
    dnf:
      name:
      - firefox
      - chromium-freeworld
      - elinks
      - thunderbird
      state: latest

  - name: SSH Server
    dnf:
      name:
        - openssh-askpass
        - openssh-clients
        - openssh-server
        - openssh
        - sshpass
        - mosh
      state: latest

  - name: Virtualization KVM
    dnf:
      name: "@virtualization"
      state: latest

  - name: Virtualization Tools
    dnf:
      name:
        - virt-install
        - virt-manager
        - virt-viewer
        - virt-what
        - bridge-utils
        - VirtualBox
      state: latest

  - name: Install Google Chrome
    dnf:
      name: google-chrome-stable
      enablerepo: google-chrome 
      state: latest

  - name: Install MariaDB
    dnf:
      name: 
        - mariadb-server
        - mariadb-server-utils
        - mycli
      state: latest

  - name: Import key VSCode
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Create VSCode File
    shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  - name: Install VSCode
    dnf:
      name: 
        - code
      state: latest

  - name: Add Docker Repository
    get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Install Docker Compose
    shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: Docker Compose permissions
    shell: chmod +x /usr/local/bin/docker-compose

  - name: Install Docker
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: Enable Docker Daemon
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add on Group Docker
    shell: usermod -a -G docker {{ fedora_user }}

  - name: Enable MariaDB Daemon
    ansible.builtin.systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: Enable SSH Daemon
    ansible.builtin.systemd:
      name: sshd
      state: started
      enabled: yes

  - name: Add on Group TCPDUMP
    shell: usermod -a -G tcpdump {{ fedora_user }}
    #vars:
    #  fedora_user: name_user

  - name: Add on Group WIRESHARK
    shell: usermod -a -G wireshark {{ fedora_user }}

  - name: Add on Group VBOXUSERS
    shell: usermod -a -G vboxusers {{ fedora_user }}

  - name: Add on Group QEMU
    shell: usermod -a -G qemu {{ fedora_user }}

  - name: Add on Group LIBVIRT
    shell: usermod -a -G libvirt {{ fedora_user }}
