---
  - hosts: all
    become: True
    roles: debian-security
    vars:
      debian_user: freddy
      debian_version: buster
      debian_kernel_version: 4.19.0-11-amd64   # uname -r
      debian_host: 10.172.0.60
      debian_private_key_file: ~/.ssh/fcch-ssh
      debian_port: 22