- block:
  - name: ADD SOURCES FILE REPOSITORYS
    template:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: "{{ debian_user }}"
      group: "{{ debian_user }}"
      mode: "0644"
  
  - name: INSTALL DEB-MULTIMEDIA KEYRING
    apt:
      deb: http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb

  - name: DEB-MULTIMEDIA REPOSITORY
    apt_repository:
      repo: deb http://www.deb-multimedia.org {{ debian_version }} main non-free
      state:  present
      filename: deb-multimedia

  - name: ADD MARIADB KEYRING
    apt_key:
      url: https://mariadb.org/mariadb_release_signing_key.asc
      state: present
  
  - name: ADD MARIADB REPOSITORY
    apt_repository:
      repo: deb [arch=amd64] http://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.4/debian {{ debian_version }} main
      state: present
      filename: mariadb

  - name: ADD MARIADB SRC REPOSITORY
    apt_repository:
      repo: deb-src [arch=amd64] http://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.4/debian {{ debian_version }} main
      state: present
      filename: mariadb

  - name: ADD VIRTUALBOX KEYRING
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present

  - name: ADD VIRTUALBOX REPOSITORY
    apt_repository:
      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ debian_version }} contrib
      state: present
      filename: virtualbox

  - name: DOCKER GPG
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: DOCKER CE
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ debian_version }} stable
      state: present
      filename: docker-ce

  - name: DOCKER CE - SRC
    apt_repository:
      repo: deb-src [arch=amd64] https://download.docker.com/linux/debian {{ debian_version }} stable
      state: present
      filename: docker-ce

  - name: TYPORA KEYRING
    apt_key: 
      url: https://typora.io/linux/public-key.asc
      state: present

  - name: TYPORA
    apt_repository:
      repo: deb https://typora.io/linux ./
      state: present
      filename: typora

  - name: UPDATE CACHE
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: UPGRADE ALL PACKAGES
    apt:
      name: "*"
      state: latest