- block:
  - name: GET KERNEL VERSION
    shell: uname -r
    register: kernel_version_output

  - debug: msg="{{ kernel_version_output.stdout }}"

  - name: INSTALL PACKAGES AFTER UPDATES
    apt:
      name: 
        - linux-headers-{{ kernel_version_output.stdout }}
      state: latest
  
  - name: INSTALL INTEL TOOLS AND SENSORS
    apt:
      name:
        - intel-microcode
        - intel-gpu-tools
        - inteltool
        - lm-sensors
      state: latest

  - name: INSTALL FIRMWARE META PACKAGES
    apt:
      name:
        - firmware-linux
        - firmware-linux-free
        - firmware-linux-nonfree
      state: latest

  - name: INSTALL PACKAGES FOR COMPRESS AND UNCOMPRESS
    apt:
      name:
        - bzip2
        - zip
        - unzip
        - unace
        - rar
        - unace-nonfree
        - p7zip
        - p7zip-full
        - p7zip-rar
        - unrar
        - unrar-free
        - lzip
        - lhasa
        - arj
        - sharutils
        - mpack
        - lzma
        - lzop
        - cabextract
        - xz-utils
      state: latest

  - name: BATERY STATUS
    apt:
      name:
        - acpi
        - acpid
        - acpitool
        - tuned
        - tuned-gtk
        - tuned-utils
      state: latest

  - name: EXTRA TOOLS
    apt:
      name:
        - wget
        - pv
        - net-tools
        - speedtest-cli
        - tree
        - locales
        - ethtool
        - mlocate
        - hardinfo
      state: latest

  - name: SSH SERVER
    apt:
      name:
        - ssh
        - rsync
        - openssh-server
        - openssh-client
        - mosh
      state: latest

  - name: FIREWALL
    apt:
      name:
        - ufw
      state: latest

  - name: KVM VIRTUALIZATION
    apt:
      name:
        - qemu-kvm
        - qemu-utils
        - libvirt-clients
        - libvirt-daemon-system
        - virt-viewer
        - virt-what
        - virtinst
        - virt-manager
      state: latest

  - name: CODECS, SOUND AND VIDEO
    apt:
      name:
        - vlc
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-pulseaudio
        - vorbis-tools faac
        - faad w64codecs
        - ffmpeg
        - ffmpeg2theora
      state: latest

  - name: FONTS TYPOGRAPHICS
    apt:
      name:
        - ttf-mscorefonts-installer
        - fonts-freefont-ttf
        - fonts-freefont-otf
      state: latest

  - name: GRAPHICS DESIGN
    apt:
      name:
        - gimp
        - gimp-data-extras
        - inkscape
        - inkscape-open-symbols
        - dia
        - dia-rib-network
        - dia-shapes
        - dia-common
        - peek
      state: latest

  - name: WEB BROWSERS
    apt:
      name:
        - chromium
        - chromium-l10n
      state: latest

  - name: GOOGLE CHROME
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: PACKAGES FOR HOBBIES
    apt:
      name:
        - ghex
        - gqrx-sdr
        - fritzing
        - fritzing-parts
        - arduino
        - arduino-core
      state: latest

  - name: VIRTUALBOX
    apt:
      name: virtualbox-6.1
      state: latest

  - name: DOCKER CE
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest